# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0005_auto_20180127_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
