# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_letter', '0006_letter_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
